databases:
  - name: cotizador-db
    plan: free
    databaseName: cotizador
    user: cotizador

services:
  - type: web
    name: cotizador-web
    runtime: node
    plan: free
    buildCommand: ./render-build.sh
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cotizador-db
          property: connectionString
      - key: APP_ACCESS_CODE
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false
      - key: VAPID_SUBJECT
        sync: false
      - key: CRON_SECRET
        sync: false
      - key: IMAP_USER
        sync: false
      - key: IMAP_PASSWORD
        sync: false
      - key: IMAP_HOST
        sync: false
      - key: IMAP_PORT
        sync: false
      - key: PC_USUARIO
        sync: false
      - key: PC_CONTRASENA
        sync: false
