const ExcelJS = require('exceljs');

const NAVY = 'FF0A0A1A';
const LIGHT = 'FFF5F6FB';
const WHITE = 'FFFFFFFF';
const INPUT_FILL = 'FFFFF6D9';
const INPUT_BORDER = 'FFE0A800';

const COMPANY = {
  nombre: 'GS TECHNOLOGIES INVESTMENTS, S.A.',
  direccion: 'Llano Bonito, Calle Francisco Rodríguez, Casa 5285',
  telefono: '6948-1130',
  ruc: '155667603-2-2018 DV 95',
  correo: 'd.sanchezv@gstechnologiespty.com',
};

// Marker cell so the parser can recognize files generated by this tool.
const MARKER = 'COTIZADOR_GS_V2';

// Column layout (matches the company's original working template):
// A Renglón | B Descripción | C Modelo del Equipo | D Unidades |
// E Costo de Distribuidor | F Costo Distribuidor+ITBM | G Gasto Total | H %G |
// I Precio Un. | J Subtotal | K ITBM | L Suma
// E, H are the only two cells the user actually types per item — everything
// else is a formula, same relationships as the original spreadsheet.

async function generateQuoteExcel({ opportunity, quote }) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Cotizador GS Technologies';
  const sheet = wb.addWorksheet('Cotización');

  sheet.getCell('N1').value = MARKER;
  sheet.getCell('N1').font = { color: { argb: WHITE }, size: 1 };

  sheet.columns = [
    { width: 6 }, { width: 34 }, { width: 16 }, { width: 9 },
    { width: 13 }, { width: 13 }, { width: 12 }, { width: 7 },
    { width: 11 }, { width: 11 }, { width: 10 }, { width: 11 },
  ];

  // ===== Header =====
  sheet.mergeCells('A1:L3');
  const header = sheet.getCell('A1');
  header.value = 'COTIZACIÓN';
  header.font = { size: 22, bold: true, color: { argb: NAVY } };
  header.alignment = { vertical: 'middle', horizontal: 'right' };

  sheet.mergeCells('A5:L5');
  cellText(sheet, 'A5', COMPANY.nombre, { bold: true, size: 12, color: NAVY });
  sheet.mergeCells('A6:L6');
  cellText(sheet, 'A6', `${COMPANY.direccion}  |  Tel: ${COMPANY.telefono}`, { size: 9, color: '565873' });
  sheet.mergeCells('A7:L7');
  cellText(sheet, 'A7', `RUC: ${COMPANY.ruc}  |  ${COMPANY.correo}`, { size: 9, color: '565873' });

  if (opportunity && opportunity.act_number) {
    sheet.mergeCells('A8:L8');
    cellText(sheet, 'A8', `Proceso PanamaCompra: ${opportunity.act_number}`, { size: 9, italic: true, color: '565873' });
  }

  // ===== Cliente =====
  let r = 10;
  sectionLabel(sheet, `A${r}`, 'CLIENTE'); r++;
  labeledRow(sheet, r, 'Nombre / Entidad:', (quote && quote.cliente_nombre) || (opportunity && opportunity.entity) || ''); r++;
  labeledRow(sheet, r, 'RUC:', (quote && quote.cliente_ruc) || ''); r++;
  labeledRow(sheet, r, 'Dirección:', (quote && quote.cliente_direccion) || (opportunity && opportunity.entity_address) || ''); r++;
  labeledRow(sheet, r, 'Ciudad:', (quote && quote.cliente_ciudad) || (opportunity && opportunity.entity_province) || 'Panamá'); r++;
  labeledRow(sheet, r, 'Forma de pago:', (quote && quote.forma_pago) || 'Crédito'); r++;
  r += 1;

  // ===== Items table =====
  const headers = ['Renglón', 'Descripción', 'Modelo del Equipo', 'Unidades', 'COSTO DE DISTRIBUIDOR', 'COSTO DISTRIBUIDOR +ITBM', 'GASTO TOTAL', '%G', 'Precio Un.', 'Subtotal', 'ITBM', 'Suma'];
  headers.forEach((h, i) => {
    const cell = sheet.getCell(r, i + 1);
    cell.value = h;
    cell.font = { bold: true, color: { argb: WHITE }, size: 8.5 };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    cell.alignment = { vertical: 'middle', horizontal: i === 1 ? 'left' : 'center', wrapText: true };
  });
  sheet.getRow(r).height = 30;
  r++;

  const items = (quote && quote.items && quote.items.length)
    ? quote.items
    : (opportunity && opportunity.items) || [];

  const firstItemRow = r;
  items.forEach((item, idx) => {
    const row = sheet.getRow(r);
    row.getCell(1).value = item.numRenglon ?? idx + 1;
    row.getCell(2).value = item.descripcion || '';
    row.getCell(3).value = item.modelo || '';
    row.getCell(4).value = item.cantidad || 0;
    row.getCell(5).value = item.costoDistribuidor || null; // <-- input del usuario
    row.getCell(6).value = { formula: `PRODUCT(1.07,E${r})`, result: 0 };
    row.getCell(7).value = { formula: `PRODUCT(F${r},D${r})`, result: 0 };
    row.getCell(8).value = item.margenG || null; // <-- input del usuario (multiplicador, ej. 1.3)
    row.getCell(8).dataValidation = {
      type: 'list',
      allowBlank: true,
      formulae: ['"1.0,1.1,1.2,1.3,1.4,1.5"'],
      showErrorMessage: true,
      errorTitle: 'Valor no válido',
      error: 'Elige un porcentaje de la lista (1.0 a 1.5).',
    };
    row.getCell(9).value = { formula: `PRODUCT(F${r},H${r})`, result: 0 };
    row.getCell(10).value = { formula: `PRODUCT(I${r},D${r})`, result: 0 };
    row.getCell(11).value = { formula: `PRODUCT(J${r},0.07)`, result: 0 };
    row.getCell(12).value = { formula: `SUM(J${r},K${r})`, result: 0 };

    [6, 7, 9, 10, 11, 12].forEach(c => { row.getCell(c).numFmt = '"B/. "#,##0.00'; });
    row.getCell(5).numFmt = '"B/. "#,##0.00';

    // Highlight the two cells the user actually needs to fill in.
    [5, 8].forEach(c => {
      row.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: INPUT_FILL } };
      row.getCell(c).border = {
        top: { style: 'thin', color: { argb: INPUT_BORDER } }, bottom: { style: 'thin', color: { argb: INPUT_BORDER } },
        left: { style: 'thin', color: { argb: INPUT_BORDER } }, right: { style: 'thin', color: { argb: INPUT_BORDER } },
      };
    });

    row.getCell(2).alignment = { wrapText: true, vertical: 'top' };
    if (idx % 2 === 1) {
      [1, 3, 4].forEach(c => { row.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LIGHT } }; });
    }
    row.eachCell(c => { c.font = { ...(c.font || {}), size: 8.5 }; });
    r++;
  });
  const lastItemRow = r - 1;

  r += 1;
  totalLine(sheet, r, 'SUBTOTAL', `SUM(J${firstItemRow}:J${lastItemRow})`); const subtotalRow = r; r++;
  totalLine(sheet, r, 'ITBM (7%)', `J${subtotalRow}*0.07`); const itbmRow = r; r++;
  totalLine(sheet, r, 'TOTAL COTIZACIÓN', `J${subtotalRow}+J${itbmRow}`, true); r++;

  r += 2;
  sectionLabel(sheet, `A${r}`, 'COMENTARIOS'); r++;
  sheet.mergeCells(`A${r}:L${r + 2}`);
  sheet.getCell(`A${r}`).value = (quote && quote.comentarios) || '';
  sheet.getCell(`A${r}`).alignment = { wrapText: true, vertical: 'top' };
  r += 4;

  sheet.mergeCells(`A${r}:L${r}`);
  const note = sheet.getCell(`A${r}`);
  note.value = 'Instrucciones: complete "COSTO DE DISTRIBUIDOR" y "%G" (resaltados) por cada ítem — el resto se calcula solo. Guarde el archivo y súbalo de nuevo en la app. El PDF final para el cliente solo mostrará Descripción, Modelo, Unidades, Precio Un. y Subtotal.';
  note.font = { italic: true, size: 8, color: { argb: '8A8CA3' } };
  note.alignment = { wrapText: true };

  return wb.xlsx.writeBuffer();
}

function cellText(sheet, ref, value, { bold, italic, size, color } = {}) {
  const cell = sheet.getCell(ref);
  cell.value = value;
  cell.font = { bold: !!bold, italic: !!italic, size: size || 10, color: { argb: 'FF' + (color || '10101F') } };
}

function sectionLabel(sheet, ref, text) {
  const cell = sheet.getCell(ref);
  cell.value = text;
  cell.font = { bold: true, size: 9, color: { argb: 'FF8A8CA3' } };
}

function labeledRow(sheet, r, label, value) {
  const l = sheet.getCell(r, 1);
  l.value = label;
  l.font = { bold: true, size: 9, color: { argb: 'FF0A0A1A' } };
  sheet.mergeCells(r, 2, r, 12);
  const v = sheet.getCell(r, 2);
  v.value = value;
  v.font = { size: 9 };
}

function totalLine(sheet, r, label, formula, bold) {
  sheet.mergeCells(r, 1, r, 9);
  const l = sheet.getCell(r, 1);
  l.value = label;
  l.font = { bold: true, size: bold ? 12 : 10, color: { argb: bold ? 'FF0A0A1A' : 'FF565873' } };
  l.alignment = { horizontal: 'right' };

  const v = sheet.getCell(r, 10);
  v.value = { formula };
  v.numFmt = '"B/. "#,##0.00';
  v.font = { bold: true, size: bold ? 12 : 10, color: { argb: bold ? 'FF1616E6' : 'FF565873' } };
  if (bold) v.border = { top: { style: 'medium', color: { argb: 'FF1616E6' } } };
}

module.exports = { generateQuoteExcel, MARKER };
