const ExcelJS = require('exceljs');

const NAVY = 'FF0A0A1A';
const BLUE = 'FF1616E6';
const LIGHT = 'FFF5F6FB';
const WHITE = 'FFFFFFFF';

const COMPANY = {
  nombre: 'GS TECHNOLOGIES INVESTMENTS, S.A.',
  direccion: 'Llano Bonito, Calle Francisco Rodríguez, Casa 5285',
  telefono: '6948-1130',
  ruc: '155667603-2-2018 DV 95',
  correo: 'd.sanchezv@gstechnologiespty.com',
};

// Marker cell so the parser can recognize files generated by this tool.
const MARKER = 'COTIZADOR_GS_V1';

async function generateQuoteExcel({ opportunity, quote }) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Cotizador GS Technologies';
  const sheet = wb.addWorksheet('Cotización');

  sheet.getCell('H1').value = MARKER;
  sheet.getCell('H1').font = { color: { argb: WHITE }, size: 1 };

  sheet.columns = [
    { width: 6 }, { width: 38 }, { width: 10 }, { width: 12 },
    { width: 16 }, { width: 16 }, { width: 16 },
  ];

  // ===== Header =====
  sheet.mergeCells('A1:G3');
  const header = sheet.getCell('A1');
  header.value = 'COTIZACIÓN';
  header.font = { size: 22, bold: true, color: { argb: NAVY } };
  header.alignment = { vertical: 'middle', horizontal: 'right' };

  sheet.mergeCells('A5:G5');
  cellText(sheet, 'A5', COMPANY.nombre, { bold: true, size: 12, color: NAVY });
  sheet.mergeCells('A6:G6');
  cellText(sheet, 'A6', `${COMPANY.direccion}  |  Tel: ${COMPANY.telefono}`, { size: 9, color: '565873' });
  sheet.mergeCells('A7:G7');
  cellText(sheet, 'A7', `RUC: ${COMPANY.ruc}  |  ${COMPANY.correo}`, { size: 9, color: '565873' });

  if (opportunity && opportunity.act_number) {
    sheet.mergeCells('A8:G8');
    cellText(sheet, 'A8', `Proceso PanamaCompra: ${opportunity.act_number}`, { size: 9, italic: true, color: '565873' });
  }

  // ===== Cliente =====
  let r = 10;
  sectionLabel(sheet, `A${r}`, 'CLIENTE'); r++;
  labeledRow(sheet, r, 'Nombre / Entidad:', (quote && quote.cliente_nombre) || (opportunity && opportunity.entity) || ''); r++;
  labeledRow(sheet, r, 'RUC:', (quote && quote.cliente_ruc) || ''); r++;
  labeledRow(sheet, r, 'Dirección:', (quote && quote.cliente_direccion) || ''); r++;
  labeledRow(sheet, r, 'Ciudad:', (quote && quote.cliente_ciudad) || 'Panamá'); r++;
  labeledRow(sheet, r, 'Forma de pago:', (quote && quote.forma_pago) || 'Crédito'); r++;
  r += 1;

  // ===== Items table =====
  const tableStartRow = r;
  const headers = ['#', 'Descripción', 'Cantidad', 'Unidad', 'Precio Ref. (gobierno)', 'PRECIO UNITARIO', 'Subtotal'];
  headers.forEach((h, i) => {
    const cell = sheet.getCell(r, i + 1);
    cell.value = h;
    cell.font = { bold: true, color: { argb: WHITE }, size: 9 };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    cell.alignment = { vertical: 'middle', horizontal: i === 1 ? 'left' : 'center', wrapText: true };
  });
  sheet.getRow(r).height = 26;
  r++;

  const items = (quote && quote.items && quote.items.length)
    ? quote.items
    : (opportunity && opportunity.items) || [];

  const firstItemRow = r;
  items.forEach((item, idx) => {
    const row = sheet.getRow(r);
    row.getCell(1).value = item.numRenglon ?? idx + 1;
    row.getCell(2).value = item.descripcion || '';
    row.getCell(3).value = item.cantidad || 0;
    row.getCell(4).value = item.unidad || '';
    row.getCell(5).value = item.precioReferencia != null ? item.precioReferencia : null;
    row.getCell(6).value = item.precioUnitario || null; // <-- lo llena el usuario
    row.getCell(7).value = { formula: `C${r}*F${r}`, result: 0 };

    row.getCell(5).numFmt = '"B/. "#,##0.00';
    row.getCell(6).numFmt = '"B/. "#,##0.00';
    row.getCell(7).numFmt = '"B/. "#,##0.00';
    row.getCell(6).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF6D9' } };
    row.getCell(6).border = { top: { style: 'thin', color: { argb: 'FFE0A800' } }, bottom: { style: 'thin', color: { argb: 'FFE0A800' } }, left: { style: 'thin', color: { argb: 'FFE0A800' } }, right: { style: 'thin', color: { argb: 'FFE0A800' } } };

    row.getCell(2).alignment = { wrapText: true, vertical: 'top' };
    if (idx % 2 === 1) {
      [1, 3, 4].forEach(c => { row.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LIGHT } }; });
    }
    row.eachCell(c => { c.font = c.font || {}; c.font.size = 9; });
    r++;
  });
  const lastItemRow = r - 1;

  r += 1;
  totalLine(sheet, r, 'SUBTOTAL', `SUM(G${firstItemRow}:G${lastItemRow})`); const subtotalRow = r; r++;
  totalLine(sheet, r, 'ITBM (7%)', `G${subtotalRow}*0.07`); const itbmRow = r; r++;
  totalLine(sheet, r, 'TOTAL', `G${subtotalRow}+G${itbmRow}`, true); r++;

  r += 2;
  sectionLabel(sheet, `A${r}`, 'COMENTARIOS'); r++;
  sheet.mergeCells(`A${r}:G${r + 2}`);
  sheet.getCell(`A${r}`).value = (quote && quote.comentarios) || '';
  sheet.getCell(`A${r}`).alignment = { wrapText: true, vertical: 'top' };
  r += 4;

  sheet.mergeCells(`A${r}:G${r}`);
  const note = sheet.getCell(`A${r}`);
  note.value = 'Instrucciones: complete la columna "PRECIO UNITARIO" (resaltada) con su precio final por ítem. Guarde el archivo y súbalo de nuevo en la app para generar el PDF definitivo.';
  note.font = { italic: true, size: 8.5, color: { argb: '8A8CA3' } };
  note.alignment = { wrapText: true };

  return wb.xlsx.writeBuffer();
}

function cellText(sheet, ref, value, { bold, italic, size, color } = {}) {
  const cell = sheet.getCell(ref);
  cell.value = value;
  cell.font = { bold: !!bold, italic: !!italic, size: size || 10, color: { argb: 'FF' + (color || '10101F') } };
}

function sectionLabel(sheet, ref, text) {
  const cell = sheet.getCell(ref);
  cell.value = text;
  cell.font = { bold: true, size: 9, color: { argb: 'FF8A8CA3' } };
}

function labeledRow(sheet, r, label, value) {
  const l = sheet.getCell(r, 1);
  l.value = label;
  l.font = { bold: true, size: 9, color: { argb: 'FF0A0A1A' } };
  sheet.mergeCells(r, 2, r, 7);
  const v = sheet.getCell(r, 2);
  v.value = value;
  v.font = { size: 9 };
}

function totalLine(sheet, r, label, formula, bold) {
  sheet.mergeCells(r, 1, r, 5);
  const l = sheet.getCell(r, 1);
  l.value = label;
  l.font = { bold: true, size: bold ? 12 : 10, color: { argb: bold ? 'FF0A0A1A' : 'FF565873' } };
  l.alignment = { horizontal: 'right' };

  const v = sheet.getCell(r, 6);
  v.value = { formula };
  v.numFmt = '"B/. "#,##0.00';
  v.font = { bold: true, size: bold ? 12 : 10, color: { argb: bold ? 'FF1616E6' : 'FF565873' } };
  if (bold) v.border = { top: { style: 'medium', color: { argb: 'FF1616E6' } } };
}

module.exports = { generateQuoteExcel, MARKER };
