const ExcelJS = require('exceljs');
const fs = require('fs');
const path = require('path');

const LOGO_PATH = path.join(__dirname, 'assets', 'logo.png');

const NAVY = 'FF0A0A1A';
const LIGHT = 'FFF5F6FB';
const WHITE = 'FFFFFFFF';
const INPUT_FILL = 'FFFFF6D9';
const INPUT_BORDER = 'FFE0A800';

const COMPANY = {
  nombre: 'GS TECHNOLOGIES INVESTMENTS, S.A.',
  direccion: 'Llano Bonito, Calle Francisco Rodríguez, Casa 5285',
  telefono: '6948-1130',
  ruc: '155667603-2-2018 DV 95',
  correo: 'd.sanchezv@gstechnologiespty.com',
};

// Marker cell so the parser can recognize files generated by this tool.
const MARKER = 'COTIZADOR_GS_V2';

// Column layout (matches the company's original working template):
// A Renglón | B Descripción | C Modelo del Equipo | D Unidades |
// E Costo de Distribuidor | F Costo Distribuidor+ITBM | G Gasto Total | H %G |
// I Precio Un. | J Subtotal | K ITBM | L Suma
// E, H are the only two cells the user actually types per item — everything
// else is a formula, same relationships as the original spreadsheet.

async function generateQuoteExcel({ opportunity, quote }) {
  const isDirecto = !!(opportunity && opportunity.source === 'directo');
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Cotizador GS Technologies';
  const sheet = wb.addWorksheet('Cotización');

  sheet.getCell('N1').value = MARKER;
  sheet.getCell('N1').font = { color: { argb: WHITE }, size: 1 };

  sheet.columns = [
    { width: 6 }, { width: 34 }, { width: 16 }, { width: 9 },
    { width: 13 }, { width: 13 }, { width: 12 }, { width: 7 },
    { width: 11 }, { width: 11 }, { width: 10 }, { width: 11 },
    { width: 14 },
  ];

  // ===== Header =====
  if (fs.existsSync(LOGO_PATH)) {
    try {
      const imageId = wb.addImage({ filename: LOGO_PATH, extension: 'png' });
      sheet.addImage(imageId, { tl: { col: 0, row: 0 }, ext: { width: 90, height: 90 } });
    } catch (e) { /* si falla la imagen, el resto de la plantilla se genera igual */ }
  }

  sheet.mergeCells('C1:L3');
  const header = sheet.getCell('C1');
  header.value = 'COTIZACIÓN';
  header.font = { size: 22, bold: true, color: { argb: NAVY } };
  header.alignment = { vertical: 'middle', horizontal: 'right' };

  sheet.mergeCells('A5:L5');
  cellText(sheet, 'A5', COMPANY.nombre, { bold: true, size: 12, color: NAVY });
  sheet.mergeCells('A6:L6');
  cellText(sheet, 'A6', `${COMPANY.direccion}  |  Tel: ${COMPANY.telefono}`, { size: 9, color: '565873' });
  sheet.mergeCells('A7:L7');
  cellText(sheet, 'A7', `RUC: ${COMPANY.ruc}  |  ${COMPANY.correo}`, { size: 9, color: '565873' });

  if (opportunity && opportunity.act_number && opportunity.source !== 'directo') {
    sheet.mergeCells('A8:L8');
    cellText(sheet, 'A8', `Proceso PanamaCompra: ${opportunity.act_number}`, { size: 9, italic: true, color: '565873' });
  }

  // ===== Cliente =====
  let r = 10;
  sectionLabel(sheet, `A${r}`, 'CLIENTE'); r++;
  labeledRow(sheet, r, 'Nombre / Entidad:', (quote && quote.cliente_nombre) || (opportunity && opportunity.entity) || ''); r++;
  labeledRow(sheet, r, 'RUC:', (quote && quote.cliente_ruc) || ''); r++;
  labeledRow(sheet, r, 'Dirección:', (quote && quote.cliente_direccion) || (opportunity && opportunity.entity_address) || ''); r++;
  labeledRow(sheet, r, 'Ciudad:', (quote && quote.cliente_ciudad) || (opportunity && opportunity.entity_province) || 'Panamá'); r++;
  labeledRow(sheet, r, 'Forma de pago:', (quote && quote.forma_pago) || 'Crédito'); r++;
  r += 1;

  // ===== Items table =====
  const headers = ['Renglón', 'Descripción', 'Modelo del Equipo', 'Unidades', 'COSTO DE DISTRIBUIDOR', 'COSTO DISTRIBUIDOR +ITBM', 'GASTO TOTAL', '%G', 'Precio Un.', 'Subtotal', 'ITBM', 'Suma', isDirecto ? 'Precio de Referencia' : 'Precio de Referencia (PanamaCompra)'];
  headers.forEach((h, i) => {
    const cell = sheet.getCell(r, i + 1);
    cell.value = h;
    cell.font = { bold: true, color: { argb: WHITE }, size: 8.5 };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    cell.alignment = { vertical: 'middle', horizontal: i === 1 ? 'left' : 'center', wrapText: true };
  });
  sheet.getRow(r).height = 30;
  r++;

  const BLANK_ROWS = 15;
  const items = (quote && quote.items && quote.items.length)
    ? quote.items
    : (opportunity && opportunity.items && opportunity.items.length)
      ? opportunity.items
      : Array.from({ length: BLANK_ROWS }, (_, i) => ({ numRenglon: i + 1, descripcion: '', modelo: '', cantidad: '' }));

  const firstItemRow = r;
  items.forEach((item, idx) => {
    const row = sheet.getRow(r);
    row.getCell(1).value = item.numRenglon ?? idx + 1;
    row.getCell(2).value = item.descripcion || '';
    row.getCell(3).value = item.modelo || '';
    row.getCell(4).value = item.cantidad || 0;
    row.getCell(5).value = item.costoDistribuidor || null; // <-- input del usuario
    row.getCell(6).value = { formula: `PRODUCT(1.07,E${r})`, result: 0 };
    row.getCell(7).value = { formula: `PRODUCT(F${r},D${r})`, result: 0 };
    row.getCell(8).value = item.margenG || null; // <-- input del usuario (multiplicador, ej. 1.3)
    row.getCell(8).dataValidation = {
      type: 'list',
      allowBlank: true,
      formulae: ['"1.0,1.1,1.2,1.3,1.4,1.5"'],
      showErrorMessage: true,
      errorTitle: 'Valor no válido',
      error: 'Elige un porcentaje de la lista (1.0 a 1.5).',
    };
    row.getCell(9).value = { formula: `PRODUCT(F${r},H${r})`, result: 0 };
    row.getCell(10).value = { formula: `PRODUCT(I${r},D${r})`, result: 0 };
    row.getCell(11).value = { formula: `PRODUCT(J${r},0.07)`, result: 0 };
    row.getCell(12).value = { formula: `SUM(J${r},K${r})`, result: 0 };
    row.getCell(13).value = item.precioReferencia != null ? item.precioReferencia : null; // dato informativo de PanamaCompra, no se edita
    row.getCell(13).font = { italic: true, size: 8.5, color: { argb: 'FF565873' } };

    [6, 7, 9, 10, 11, 12, 13].forEach(c => { row.getCell(c).numFmt = '"B/. "#,##0.00'; });
    row.getCell(5).numFmt = '"B/. "#,##0.00';

    // Highlight the two cells the user actually needs to fill in.
    [5, 8].forEach(c => {
      row.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: INPUT_FILL } };
      row.getCell(c).border = {
        top: { style: 'thin', color: { argb: INPUT_BORDER } }, bottom: { style: 'thin', color: { argb: INPUT_BORDER } },
        left: { style: 'thin', color: { argb: INPUT_BORDER } }, right: { style: 'thin', color: { argb: INPUT_BORDER } },
      };
    });

    row.getCell(2).alignment = { wrapText: true, vertical: 'top' };
    if (idx % 2 === 1) {
      [1, 3, 4].forEach(c => { row.getCell(c).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: LIGHT } }; });
    }
    row.eachCell(c => { c.font = { ...(c.font || {}), size: 8.5 }; });
    r++;
  });
  const lastItemRow = r - 1;

  r += 1;
  totalLine(sheet, r, 'SUBTOTAL', `SUM(J${firstItemRow}:J${lastItemRow})`); const subtotalRow = r; r++;
  totalLine(sheet, r, 'ITBM (7%)', `J${subtotalRow}*0.07`); const itbmRow = r; r++;
  totalLine(sheet, r, 'TOTAL COTIZACIÓN', `J${subtotalRow}+J${itbmRow}`, true); const totalRow = r; r++;

  // ===== Verificación contra el precio de referencia de PanamaCompra =====
  // No aplica a cotizaciones directas: no hay pliego ni precio de referencia
  // con qué comparar, así que la sección completa se omite.
  if (!isDirecto) {
    r += 2;
    sectionLabel(sheet, `A${r}`, 'VERIFICACIÓN DE PRECIO DE REFERENCIA'); r++;
    totalLine(sheet, r, 'Suma "Precio de Referencia" de los ítems', `SUM(M${firstItemRow}:M${lastItemRow})`); const refSumRow = r; r++;

    const refPrecioSistema = (opportunity && opportunity.reference_price != null) ? Number(opportunity.reference_price) : null;
    if (refPrecioSistema != null) {
      totalLine(sheet, r, 'Precio de referencia del sistema (PanamaCompra)', String(refPrecioSistema)); const refSistemaRow = r; r++;
      totalLine(sheet, r, 'Diferencia', `J${refSumRow}-J${refSistemaRow}`); const refDiffRow = r; r++;

      sheet.mergeCells(r, 1, r, 9);
      const checkLabel = sheet.getCell(r, 1);
      checkLabel.value = 'Verificación';
      checkLabel.font = { bold: true, size: 10, color: { argb: 'FF565873' } };
      checkLabel.alignment = { horizontal: 'right' };
      sheet.mergeCells(r, 10, r, 13);
      const checkCell = sheet.getCell(r, 10);
      checkCell.value = { formula: `IF(ROUND(J${refDiffRow},2)=0,"✓ Coincide con el precio de referencia","⚠ No coincide con el precio de referencia")` };
      checkCell.font = { bold: true, size: 10 };
      const checkRow = r;
      r++;

      sheet.addConditionalFormatting({
        ref: `J${checkRow}:M${checkRow}`,
        rules: [
          { type: 'containsText', operator: 'containsText', text: '✓', style: { font: { color: { argb: 'FF1FA971' }, bold: true } } },
          { type: 'containsText', operator: 'containsText', text: '⚠', style: { font: { color: { argb: 'FFC0392B' }, bold: true } } },
        ],
      });
    } else {
      sheet.mergeCells(r, 1, r, 13);
      const noRef = sheet.getCell(r, 1);
      noRef.value = 'PanamaCompra no indicó un precio de referencia total para este proceso — no hay con qué comparar.';
      noRef.font = { italic: true, size: 9, color: { argb: 'FF8A8CA3' } };
      r++;
    }
  }

  // ===== Análisis de rentabilidad (gasto vs. ganancia, con barras nativas de Excel) =====
  r += 2;
  sectionLabel(sheet, `A${r}`, 'ANÁLISIS DE RENTABILIDAD'); r++;
  totalLine(sheet, r, 'Gasto total', `SUM(G${firstItemRow}:G${lastItemRow})`); const gastoTotalRow = r; r++;
  totalLine(sheet, r, 'Precio final (total cotización)', `J${totalRow}`); const precioFinalRow = r; r++;
  totalLine(sheet, r, 'Ganancia', `J${precioFinalRow}-J${gastoTotalRow}`, true); const gananciaRow = r; r++;
  totalLine(sheet, r, 'Ganancia % sobre el costo', `J${gananciaRow}/J${gastoTotalRow}`, false, '0.0%'); r++;

  r += 1;
  sectionLabel(sheet, `A${r}`, 'Composición del precio: gasto vs. ganancia'); r++;
  const compGastoRow = r;
  totalLine(sheet, r, 'Gasto total', `J${gastoTotalRow}`); r++;
  const compGananciaRow = r;
  totalLine(sheet, r, 'Ganancia', `J${gananciaRow}`); r++;

  r += 1;
  sectionLabel(sheet, `A${r}`, 'Precio final por % de ganancia estipulado (mismo gasto total)'); r++;
  const tierRows = [];
  [0, 10, 20, 30, 40, 50].forEach(pct => {
    tierRows.push(r);
    totalLine(sheet, r, `${pct}% de ganancia`, `J${gastoTotalRow}*${1 + pct / 100}`);
    r++;
  });
  const tier50Row = tierRows[tierRows.length - 1];
  const actualRow = r;
  totalLine(sheet, r, 'ACTUAL (tu cotización)', `J${precioFinalRow}`, true);
  r++;

  // Barras nativas de Excel (dataBar): todas comparten la misma escala
  // 0 -> valor del 50% de ganancia, que nunca se supera porque el dropdown
  // %G del Excel tiene tope 1.5 (50%). Así las barras son comparables entre sí.
  const barConfig = [
    { row: compGastoRow, color: 'FF1616E6' },
    { row: compGananciaRow, color: 'FF1FA971' },
    ...tierRows.map(row => ({ row, color: 'FF8A8CA3' })),
    { row: actualRow, color: 'FF1FA971' },
  ];
  barConfig.forEach(({ row, color }) => {
    sheet.addConditionalFormatting({
      ref: `J${row}:J${row}`,
      rules: [{
        type: 'dataBar',
        cfvo: [{ type: 'num', value: 0 }, { type: 'formula', value: `$J$${tier50Row}` }],
        color: { argb: color },
        minLength: 0, maxLength: 100, showValue: true, gradient: false, border: false,
      }],
    });
  });

  r += 2;
  sectionLabel(sheet, `A${r}`, 'COMENTARIOS'); r++;
  sheet.mergeCells(`A${r}:L${r + 2}`);
  sheet.getCell(`A${r}`).value = (quote && quote.comentarios) || '';
  sheet.getCell(`A${r}`).alignment = { wrapText: true, vertical: 'top' };
  r += 4;

  sheet.mergeCells(`A${r}:L${r}`);
  const note = sheet.getCell(`A${r}`);
  note.value = 'Instrucciones: complete "COSTO DE DISTRIBUIDOR" y "%G" (resaltados) por cada ítem — el resto, incluyendo la verificación del precio de referencia y el análisis de rentabilidad de abajo, se calcula solo. Guarde el archivo y súbalo de nuevo en la app. El PDF final para el cliente solo mostrará Descripción, Modelo, Unidades, Precio Un. y Subtotal (no el análisis interno).';
  note.font = { italic: true, size: 8, color: { argb: '8A8CA3' } };
  note.alignment = { wrapText: true };

  return wb.xlsx.writeBuffer();
}

function cellText(sheet, ref, value, { bold, italic, size, color } = {}) {
  const cell = sheet.getCell(ref);
  cell.value = value;
  cell.font = { bold: !!bold, italic: !!italic, size: size || 10, color: { argb: 'FF' + (color || '10101F') } };
}

function sectionLabel(sheet, ref, text) {
  const cell = sheet.getCell(ref);
  cell.value = text;
  cell.font = { bold: true, size: 9, color: { argb: 'FF8A8CA3' } };
}

function labeledRow(sheet, r, label, value) {
  const l = sheet.getCell(r, 1);
  l.value = label;
  l.font = { bold: true, size: 9, color: { argb: 'FF0A0A1A' } };
  sheet.mergeCells(r, 2, r, 12);
  const v = sheet.getCell(r, 2);
  v.value = value;
  v.font = { size: 9 };
}

function totalLine(sheet, r, label, formula, bold, numFmt) {
  sheet.mergeCells(r, 1, r, 9);
  const l = sheet.getCell(r, 1);
  l.value = label;
  l.font = { bold: true, size: bold ? 12 : 10, color: { argb: bold ? 'FF0A0A1A' : 'FF565873' } };
  l.alignment = { horizontal: 'right' };

  const v = sheet.getCell(r, 10);
  v.value = { formula };
  v.numFmt = numFmt || '"B/. "#,##0.00';
  v.font = { bold: true, size: bold ? 12 : 10, color: { argb: bold ? 'FF1616E6' : 'FF565873' } };
  if (bold) v.border = { top: { style: 'medium', color: { argb: 'FF1616E6' } } };
}

module.exports = { generateQuoteExcel, MARKER };
